version: "3.9"
services:
  youtube-record:
    build: .
    image: youtube-record
    volumes:
      - ${RecordPath:-./record}:/output
      - ${TempPath:-./record}:/temp_path
      - ${UnArchivedPath:-./unarchived}:/unarchived_stream
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env