version: "3.9"
services:
  youtube-record:
    build: .
    image: youtube-record:latest
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${RecordPath:-./record}:/output
      - ${TempPath:-./record}:/temp_path
      - ${UnArchivedPath:-./unarchived}:/unarchived_stream
      - ${CookiesFilePath:-./cookies.txt}:/app/cookies.txt
    env_file:
      - .env