services:
  stream-record-master:
    container_name: stream-record-master
    image: jun112561/stream-record-tools:master
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${RecordPath:-./record}:/output
      - ${TempPath:-./record}:/temp_path
      - ${UnArchivedPath:-./unarchived}:/unarchived_stream
      - ${MemberOnlyPath:-./member_only}:/member_only_stream
      - ${CookiesFilePath:-./cookies.txt}:/app/cookies.txt
    env_file:
      - .env
    restart: unless-stopped
    networks:
      stream-record-tools:
        ipv4_address: 172.28.0.2

networks:
  stream-record-tools:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1